--=======PART B: USER ROLES & SECURITY========

-- CREATING ROLES
CREATE ROLE SalesRole
CREATE ROLE HRRole
CREATE ROLE DBA_Role

-- ASSIGNING PERMISSIONS
-- FOR SALESROLE
GRANT SELECT, INSERT, UPDATE ON SCHEMA::Sales TO SalesRole
DENY SELECT ON SCHEMA::HumanResources TO SalesRole

-- FOR HRROLE
GRANT SELECT, INSERT, UPDATE ON SCHEMA::HumanResources TO HRRole
DENY SELECT ON SCHEMA::Sales TO HRRole

-- FOR DBA_ROLE
GRANT CONTROL ON DATABASE::AdventureWorks2022 TO DBA_Role

-- CREATING LOGINS
CREATE LOGIN SalesUserLogin WITH PASSWORD = 'Sales123'
CREATE LOGIN HRUserLogin WITH PASSWORD = 'HR123'
CREATE LOGIN DBAUserLogin WITH PASSWORD = 'DBA123'

-- CREATING USERS
CREATE USER SalesUser FOR LOGIN SalesUserLogin
CREATE USER HRUser FOR LOGIN HRUserLogin
CREATE USER DBAUser FOR LOGIN DBAUserLogin

-- ASSIGNING ROLES TO USERS
ALTER ROLE SalesRole ADD MEMBER SalesUser
ALTER ROLE HRRole ADD MEMBER HRUser
ALTER ROLE DBA_Role ADD MEMBER DBAUser

--=========TESTING==========

-- TEST SalesUser
EXECUTE AS USER = 'SalesUser'

-- SHOULD WORK
SELECT * FROM Sales.Customer
UPDATE Sales.Customer SET ModifiedDate = '2022-02-02' WHERE CustomerID = 1

-- SHOULD FAIL
SELECT * FROM HumanResources.Employee
UPDATE HumanResources.Employee SET JobTitle = 'CLEANER' WHERE BusinessEntityID = 1

REVERT

-- TEST HRUser
EXECUTE AS USER = 'HRUser'

-- SHOULD FAIL
SELECT * FROM Sales.Customer
UPDATE Sales.Customer SET ModifiedDate = '2022-02-02' WHERE CustomerID = 1

-- SHOULD WORK
SELECT * FROM HumanResources.Employee
UPDATE HumanResources.Employee SET JobTitle = 'CLEANER' WHERE BusinessEntityID = 1

REVERT

-- TEST DBAUser
EXECUTE AS USER = 'DBAUser'

-- SHOULD WORK (full access)
SELECT * FROM Sales.Customer
SELECT * FROM HumanResources.Employee

REVERT
