--=======PART D: BACKUP & RECOVERY========

---BACKUP THE DATABASE

-- FULL BACKUP
BACKUP DATABASE AdventureWorks2022
TO DISK = 'C:\SQLBackups\AdventureWorks2022_Full.bak'
WITH INIT, FORMAT

-- DIFFERENTIAL BACKUP
BACKUP DATABASE AdventureWorks2022
TO DISK = 'C:\SQLBackups\AdventureWorks2022_DIFF.bak'
WITH DIFFERENTIAL

-- TRANSACTION LOG BACKUP
BACKUP LOG AdventureWorks2022
TO DISK = 'C:\SQLBackups\AdventureWorks2022_LOG.trn'


---RESTORE THE DATABASE

-- STEP 1: RESTORE FULL BACKUP
RESTORE DATABASE AdventureWorks2022
FROM DISK = 'C:\SQLBackups\AdventureWorks2022_Full.bak'
WITH NORECOVERY

-- STEP 2: RESTORE DIFFERENTIAL BACKUP
RESTORE DATABASE AdventureWorks2022
FROM DISK = 'C:\SQLBackups\AdventureWorks2022_DIFF.bak'
WITH NORECOVERY

-- STEP 3: RESTORE TRANSACTION LOG (brings DB online)
RESTORE LOG AdventureWorks2022
FROM DISK = 'C:\SQLBackups\AdventureWorks2022_LOG.trn'
WITH RECOVERY
